AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront distribution with S3 origin (OAC) for React/Vite SPA, with SPA routing fallbacks.

Parameters:
  ProjectName:
    Type: String
    Default: neuroforge-web
    Description: Logical project name to tag resources.
  BucketName:
    Type: String
    Default: ""
    Description: Optional S3 bucket name. Leave blank to auto-generate a unique name.
  PriceClass:
    Type: String
    Default: PriceClass_100
    AllowedValues: [PriceClass_100, PriceClass_200, PriceClass_All]
    Description: CloudFront price class.
  AcmCertificateArn:
    Type: String
    Default: ""
    Description: Optional ACM cert ARN in us-east-1 for a custom domain. Leave blank to use default *.cloudfront.net cert.
  AlternativeDomainNames:
    Type: CommaDelimitedList
    Default: ""
    Description: Optional comma-separated domain names for the distribution (e.g., app.example.com,www.example.com).

Conditions:
  HasBucketName: !Not [!Equals [!Ref BucketName, ""]]
  HasCustomCert: !Not [!Equals [!Ref AcmCertificateArn, ""]]
  HasAltNames: !Not [!Equals [!Join [",", !Ref AlternativeDomainNames], ""]]

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [HasBucketName, !Ref BucketName, !Ref AWS::NoValue]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${AWS::StackName}-oac'
        Description: Access control for CloudFront to reach S3 origin.
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: !Ref PriceClass
        Comment: !Sub '${ProjectName} CloudFront distribution'
        DefaultRootObject: index.html
        Aliases: !If [HasAltNames, !Ref AlternativeDomainNames, []]
        Origins:
          - Id: s3-origin
            DomainName: !GetAtt SiteBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref OriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: s3-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
        ViewerCertificate: !If
          - HasCustomCert
          - AcmCertificateArn: !Ref AcmCertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        HttpVersion: http2and3

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServiceRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${SiteBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}'

Outputs:
  BucketNameOut:
    Description: Name of the S3 bucket hosting the site.
    Value: !Ref SiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  DistributionId:
    Description: CloudFront distribution ID.
    Value: !Ref Distribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'
  DistributionDomainName:
    Description: CloudFront domain name.
    Value: !GetAtt Distribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DistributionDomainName'
